name: Run Backend Tests

on:
    push:
        paths:
            - 'backend/**'
            - '.github/workflows/backend-tests.yml'
    pull_request:
        paths:
            - 'backend/**'
            - '.github/workflows/backend-tests.yml'

jobs:
    test:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: backend
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.13.7"
            
            - name: Install dependencies
              uses: |
               pip install -r requirements.txt
               pip install pytest
            
            - name: Run Pytest
              run: python -m pytest